services:
  bd_campo_deportivo:
    image: mysql:8.0
    ports:
      - "3310:3306" # Cambiamos la puerta externa al 3310 para evitar conflictos
    environment:
      - MYSQL_ROOT_PASSWORD=C4mpoDeportivo2026!
      - MYSQL_DATABASE=reservas_campo
    volumes:
      - mysql_data:/var/lib/mysql # <-- 1. MAPEO DEL VOLUMEN

volumes:
  mysql_data: # <-- 2. DECLARACIÓN DEL VOLUMEN
